export const studentDetails = [
    {   id: 1, 
        lastName: 'Everdeen', 
        firstName: 'Evelyn', 
        age: 35, 
        avatar: 'https://randomuser.me/api/portraits/women/11.jpg',
        dateOfBirth: '10.12.1986',
        job: 'Web Development Student',
        email: 'e.everdeen@gmail.com',
        phone: '+1 234 567 89',
        location: 'Utrecht, The Netherlands'
    },
    {   id: 2, 
        lastName: 'Rembrandt', 
        firstName: 'Aranka', 
        age: 42, 
        avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
        dateOfBirth: '01.02.1980',
        job: 'UI Designer',
        email: 'arankarembrandt18@hotmail.com',
        phone: '+1 234 567 89',
        location: 'Purmerend, The Netherlands'
    },
    {   id: 3, 
        lastName: 'van Rosemondt', 
        firstName: 'Floris', 
        age: 45, 
        avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
        dateOfBirth: '12.04.1977',
        job: 'Cabin Attendent',
        email: 'flo_van_floris@hotmail.com',
        phone: '+1 234 567 89',
        location: 'Roosendaal, The Netherlands'
    },
    {   id: 4, 
        lastName: 'Jonas', 
        firstName: 'Hector', 
        age: 22, 
        avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
        dateOfBirth: '03.02.2000',
        job: 'Barista',
        email: 'jonas_de_ponas_2000@live.com',
        phone: '+1 234 567 89',
        location: 'Hengelo, The Netherlands'
    },
    {   id: 5, 
        lastName: 'Churandy', 
        firstName: 'Martina', 
        age: 33, 
        avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
        dateOfBirth: '12.12.1988',
        job: 'Accountant',
        email: 'martina_c@hotmail.com',
        phone: '+1 234 567 89',
        location: 'Leeuwarden, The Netherlands'
    },
    {   id: 6, 
        lastName: 'Dirkse', 
        firstName: 'Rahima', 
        age: 31, 
        avatar: 'https://randomuser.me/api/portraits/women/33.jpg',
        dateOfBirth: '12.04.1991',
        job: 'Human Resources Manager',
        email: 'rahima_dirkse@gmail.com',
        phone: '+1 234 567 89',
        location: 'Rotterdam, The Netherlands'
    },
    {   id: 7, 
        lastName: 'Bullock', 
        firstName: 'Sandra', 
        age: 44, 
        avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
        dateOfBirth: '05.05.1978',
        job: 'Actress',
        email: 's_bullock0505@hotmail.com',
        phone: '+1 234 567 89',
        location: 'Almere, The Netherlands'
    },
    {   id: 8, 
        lastName: 'van Wees', 
        firstName: 'Wietske', 
        age: 36, 
        avatar: 'https://randomuser.me/api/portraits/men/44.jpg',
        dateOfBirth: '13.10.1986',
        job: 'Zookeeper',
        email: 'wv4nw33a@hotmail.com',
        phone: '+1 234 567 89',
        location: 'Emmen, The Netherlands'
    },
    {   id: 9, 
        lastName: 'Trooper', 
        firstName: 'Storm', 
        age: '', 
        avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
        dateOfBirth: '19 BBY',
        job: 'Army Soldier',
        email: 'TK_stormtrooper_18283@starwars.com',
        phone: '',
        location: 'Daro, The Outer Rim Territories | Imperial-Era'
    },
];